### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by nonunknown** [GabrieleTorini/godot-behavior-tree#15]
Ok, I've found some things that could be changed to improve optimization max as possible:

### Behavior_tree.gd

* The debug option,( seems to make no difference here?):
![image](https://user-images.githubusercontent.com/58845030/112549300-59722700-8d9c-11eb-8922-642f271a941f.png)

* Remove the Red box, and add the green one:

![image](https://user-images.githubusercontent.com/58845030/112549978-68a5a480-8d9d-11eb-81c3-7501627ff59a.png)

### Other

I looked at other scripts, there's nothing more I can find to improve

### About a Manager

What you can do is a manager script (tool) that check for the "BehaviorTree" node in the current edited scene, and check at every tree_changed event if the childs are correct (number of childs, expected child node, and so on)

### Debug Stuff

I think that, instead of checking if (debug) everytime, you can make debug functions to be called instead of the main ones e.g:
`run()` and `run_debug()`. Or new classes like `Selector` and `SelectorDebug`, there are lots of ways.

### Final Toughts

* My english is not one of the bests, but I think I've passed the essence of things here
* This ideas are not mandatory, but just some toughts that can evolve...

**Comment by MadFlyFish** [comment]
Looking forward to new updates LOL

**Comment by GabrieleTorini** [comment]
@MadFlyFish Updates are coming in.. slowly lol. There has been progress but have to ensure backwards compatibility. Or maybe no, if people are fine with it.

**Comment by MadFlyFish** [comment]
> @MadFlyFish Updates are coming in.. slowly lol. There has been progress but have to ensure backwards compatibility. Or maybe no, if people are fine with it.

Great to hear that!
Backwards compatibility maybe not the most important thing. I am fine with it, if it's necessary to break compatibility.
