### ISSUE TITLE
Invalid operands "String" and "Int" in operrate "=="

### ISSUE THREAD

**Issue by MadFlyFish** [GabrieleTorini/godot-behavior-tree#24]
It seems that there are several other similar errors since 1.2 :)
for example, BTAlways, BTGuard, BTRepeatUntil, 
![image](https://user-images.githubusercontent.com/36298330/116658450-88df0980-a9c2-11eb-9bc6-ef577674f09d.png)

**Comment by GabrieleTorini** [comment]
The error is not where you drew the arrows.
You need to reassign the always_what flag in the inspector. Have you downloaded the new 1.2.rc4 branch?

**Comment by MadFlyFish** [comment]
Not yet， but I will check it out soon.

**Comment by GabrieleTorini** [comment]
> Not yet， but I will check it out soon.

It's in main now :)

**Comment by MadFlyFish** [comment]
Yep, now it works fine in rc4
