### ISSUE TITLE
C++ Custom Native Module

### ISSUE THREAD

**Issue by felaugmar** [GabrieleTorini/godot-behavior-tree#27]
I'm amazed by this plugin, do you have interest in creating a secondary branch with a [native custom module](https://docs.godotengine.org/en/stable/development/cpp/custom_modules_in_cpp.html) implementation?

It requires re-compilation of the editor to be used, but would add nice features like the classes documentation in **Search Help** and better runtime performance.

**Comment by GabrieleTorini** [comment]
That'd be great. I am not updating this plugin anytime soon and if I did I would be re-designing it entirely (especially to avoid coroutines, which turned out to be the core of the implementation, unfortunately, and some conceptual changes), but turning it into a module seems like a good idea especially for performance.

**Comment by felaugmar** [comment]
I'll start working on it and see what happens.

**Comment by GabrieleTorini** [comment]
If you could go through the hassle of setting up the module, gdnative etc. and implementing the plugin as it is now, I'd be happy to hop in and proceed to do that big re-design.

**Comment by felaugmar** [comment]
I've experimented GDNative for a long time and I found out that C++ modules are still the way to go in the native side, GDNative doesn't work pretty well yet.
So I'll implement the plugin as it is now as a C++ module, trying to keep full compatibility with the GDScript version.

I'm curious about your re-design choices :)

**Comment by GabrieleTorini** [comment]
Ok that's great. 
I myself have experience with C++ (outside of Godot) from back when I was attempting to make games from scratch with DirectX. I'm happy to work with C++ but have no experience with Godot modules, so it would be a very interesting experience, with your help. Looking forward to that! :)

(If you wanna discuss anything, I'm on Discord: kagenashi#8224

**Comment by felaugmar** [comment]
I've decided to not advance on the implementation.
